# Generated by Django 3.2.7 on 2021-09-28 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_rating_movie'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RaitingStar',
            new_name='RatingStar',
        ),
        migrations.AlterField(
            model_name='rating',
            name='ip',
            field=models.CharField(max_length=15, verbose_name='IP адресс'),
        ),
    ]
