# Generated by Django 3.2.7 on 2021-09-28 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20210928_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='photo',
            field=models.ImageField(null=True, upload_to='actors', verbose_name='фото'),
        ),
    ]
