# Generated by Django 3.2.7 on 2021-10-04 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_actor_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='about',
            field=models.TextField(blank=True, verbose_name='Биография'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='actors', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='director',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='directors', verbose_name='фото'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='tagline',
            field=models.CharField(blank=True, max_length=255, verbose_name='Слоган'),
        ),
        migrations.AlterField(
            model_name='movieshot',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shots', to='catalog.movie', verbose_name='Фильм'),
        ),
    ]
