# Generated by Django 3.2.7 on 2021-10-08 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_auto_20211008_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='posted_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
