# Generated by Django 3.2.7 on 2021-10-08 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_alter_review_posted_on'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ('-posted',), 'verbose_name': 'отзыв', 'verbose_name_plural': 'отзывы'},
        ),
        migrations.RenameField(
            model_name='review',
            old_name='posted_on',
            new_name='posted',
        ),
    ]
