# Generated by Django 3.2.7 on 2021-10-14 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_alter_review_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ratingstar',
            options={'ordering': ('-value',), 'verbose_name': 'звезду рейтинга', 'verbose_name_plural': 'здезды рейтинга'},
        ),
        migrations.AlterField(
            model_name='ratingstar',
            name='value',
            field=models.PositiveSmallIntegerField(default=0, unique=True, verbose_name='Значение'),
        ),
        migrations.AlterField(
            model_name='review',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='catalog.review', verbose_name='Ответ на комментарий'),
        ),
    ]
