# Generated by Django 3.2.7 on 2021-10-25 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_auto_20211021_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='director',
            name='about_en',
            field=models.TextField(blank=True, null=True, verbose_name='биография'),
        ),
        migrations.AddField(
            model_name='director',
            name='about_ru',
            field=models.TextField(blank=True, null=True, verbose_name='биография'),
        ),
        migrations.AddField(
            model_name='director',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='ФИО'),
        ),
        migrations.AddField(
            model_name='director',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='ФИО'),
        ),
    ]
