# Generated by Django 3.2.7 on 2021-10-25 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_auto_20211025_0626'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='poster_en',
            field=models.ImageField(null=True, upload_to='movies', verbose_name='Постер'),
        ),
        migrations.AddField(
            model_name='movie',
            name='poster_ru',
            field=models.ImageField(null=True, upload_to='movies', verbose_name='Постер'),
        ),
    ]
