# Generated by Django 3.2.7 on 2021-10-27 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_auto_20211027_1350'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MovieShot',
        ),
    ]
