# Generated by Django 3.2.7 on 2021-10-29 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0022_alter_rating_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='star',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='catalog.ratingstar', verbose_name='Звезда'),
        ),
    ]
