# Generated by Django 3.2.7 on 2021-10-30 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0023_alter_rating_star'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='ip',
            field=models.CharField(max_length=15, unique=True, verbose_name='IP адрес'),
        ),
    ]
