# Generated by Django 3.2.7 on 2021-11-01 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0026_alter_movie_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratingstar',
            name='url',
            field=models.SlugField(max_length=255, null=True, verbose_name='Ссылка'),
        ),
    ]
