# Generated by Django 3.2.7 on 2021-11-01 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0027_ratingstar_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratingstar',
            name='url',
            field=models.SlugField(max_length=255, unique=True, verbose_name='Ссылка'),
        ),
    ]
